site_name: ReLeLa
theme: readthedocs
repo_url: https://dccuchile.github.io/ReLeLa/
site_description: REpresentation LEarning + Natural LAnguage Processing Group (ReLeLa)
nav:
    - Home: index.md
    - Courses: courses.md
    - Projects: projects.md
    - Seminars: seminars.md
    - Publications: publications.md  
