site_name: ReLeLa
theme: cluster
site_description: Representations for Learning and Language (ReLeLa) research group. 
nav:
    - Home: index.md
    - Seminars: seminars.md
    - Publications: publications.md 
    - Computing Resources: resources.md
    - Ciclos de Charlas: ciclos.md  
