site_name: ReLeLa
theme: cluster
site_description: REpresentation LEarning + Natural LAnguage Processing Group (ReLeLa)
nav:
    - Home: index.md
    - Courses: courses.md
    - Projects: projects.md
    - Seminars: seminars.md
    - Publications: publications.md 
    - Computing Resources: resources.md
      
